#  version of docker-compose
version: "3.9"
# types of containers
services:
  # name of container
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app
    depends_on:
      - server
    restart: always
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    restart: always